MODEL:
  TYPE: swin
  NAME: simmim_lineval
  DROP_PATH_RATE: 0.1
  SWIN:
    EMBED_DIM: 64
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 6
DATA:
  DATASET: 'stl10'
  IMG_SIZE: 96
TRAIN:
  EPOCHS: 100
  WARMUP_EPOCHS: 20
  BASE_LR: 1.25e-3
  WARMUP_LR: 2.5e-7
  MIN_LR: 2.5e-7
  WEIGHT_DECAY: 0.05
  LAYER_DECAY: 0.9
LIN_EVAL: True
PRINT_FREQ: 100
SAVE_FREQ: 100
TAG: simmim_lineval__swin_small__img96_window6__100ep